### ISSUE TITLE
'Context' object has no attribute 'user_preferences'

### ISSUE THREAD

**Issue by jaccosteur** [vvoovv/blender-geo#117]
Hi,

Hope you are doing well. Today I purchased your  openstreet addon and installed it as the manual suggests. (Import the zipped file using the import in the addon part of the preferences of blender 2.8.

When I then try to run the quick check that should show me the kremlin I get this error:
'Context' object has no attribute 'user_preferences'

Looking in the script, it fails on the script __init__.py at line 409. It can not find the module.

Please advice.

**Comment by jaccosteur** [comment]
In porting issues I see this is the problem:
context.user_preferences -> context.preferences

I can try and see what happens.

Looks like 2.8 porting is in progress.

**Comment by jaccosteur** [comment]
It still produces errors. ;-(

**Comment by jaccosteur** [comment]
I changed all the user_preferences occurences to preferences and at least the import works now.

Jacco.

**Comment by jaccosteur** [comment]
So I changed context.user_preferences to context.preferences in all __init__ files that contained this.

**Comment by vvoovv** [comment]
@jaccosteur,
Thank you very much for purchasing the blender-osm addon!

Yes, you are right. The Blender developers have renamed the propery _user_preferences_ to _preferences_ recently. So the addon worked with the previous releases of the Blender 2.80 Beta and stopped to work in the latest releases.

I'll provide update till the end of the week.

**Comment by vvoovv** [comment]
@jaccosteur,
Please use the link in your purchase confirmation e-mail to download the blender-osm addon that works with the latest Blender 2.80 Beta.

Please inform me if you encounter any problem

**Comment by John5i4** [comment]
It would seem that they changed it back to preferences. I'm getting the error:
'Context' object has no attribute 'preferences'

**Comment by vvoovv** [comment]
@John5i4 when did you download the Blender 2.80 Beta?

**Comment by John5i4** [comment]
Alright, I'm sorry, I should have thought of that right away. My 2.8 version was a month old. Thanks for reminding me...

**Comment by vvoovv** [comment]
it has been fixed, so closing the issue
